version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: wallet-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    depends_on:
      - postgres
    ports:
      - "${SPRING_PORT}:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PORT: ${SPRING_PORT}
    restart: always

volumes:
  postgres_data: